name: nanoutil
description: Tools for the NANO and BANANO cryptocurrencies including key generation, signing, encryption, and more.
version: 1.0.1
homepage: https://github.com/perishllc/nanoutil

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  nanodart: ^2.0.0
  ed25519_hd_key: ^2.2.0
  libcrypto: ^0.2.1
  decimal: ^2.3.0

dev_dependencies:
  pedantic: ^1.11.1
  test: ^1.17.10